# Generated by Django 4.0.4 on 2022-04-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_category', '0001_initial'),
        ('eshop_products', '0002_product1_product2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product1',
            name='categories',
            field=models.ManyToManyField(blank=True, to='eshop_products_category.productcategory'),
        ),
        migrations.AddField(
            model_name='product2',
            name='categories',
            field=models.ManyToManyField(blank=True, to='eshop_products_category.productcategory'),
        ),
    ]
